USE MovieDB

DBCC CHECKIDENT (actor, RESEED, 0)
DBCC CHECKIDENT (genre, RESEED, 0)
DBCC CHECKIDENT (movie, RESEED, 0)
DBCC CHECKIDENT (movieCollection, RESEED, 0)
DBCC CHECKIDENT (movieUser, RESEED, 0)
DBCC CHECKIDENT (regisseur, RESEED, 0)